### ISSUE TITLE
ImportError: No module named kodicmd.shell

### ISSUE THREAD

**Issue by scrdcow** [tobias-d-oe/kodicmd#1]
I bet this is pretty trivial, but since I don't know python or programming that well. I get the following error ater running kodicmd...

Traceback (most recent call last):
  File "/usr/local/bin/kodicmd", line 96, in <module>
    from kodicmd.shell import KodiShell
ImportError: No module named kodicmd.shell

I found no file named kodicmd.shell on the system.

**Comment by tobias-d-oe** [comment]
Hi,
kodicmd.shell is not a file its a bit code located in a library file.
I think you tried to start kodicmd directly, after the script needs library files this is not directly possible.
The simplest way is to run "python setup.py install" after this kodicmd is installed in your system and python can find the required libraries.
Or you can try to add this line to the script in line 29 (untested!):
---8<---
sys.path.append('.')
--->8---

**Comment by scrdcow** [comment]
Hello and thanks for the help! :-)

I did not manage thou. I'm sorry, I was not precise... I understood that it might not be a file aswell but my limited python understanding hinders me from adequate problemsolving. A missing file would be easy to find and add.
I did run the setup beforehand. The error occurs when running the installed kodicmd without any arguments. I did try adding the line to line 29, both as "import sys.path.append('.')" or as a line in itself before, after and without "import sys". Did this before installing, deleted old files, then re-installed. But I only get...

  File "/usr/local/bin/kodicmd", line 29
    import sys.path.append('.')
                          ^
SyntaxError: invalid syntax


...in the first case, or "NameError: name 'sys' is not defined" if it's placed before "import sys" or without it. I get the old error if it's placed after.

I'm on Debian unstable and the package got installed under python 2.7 btw.
